---
# Source: hello-world-deployment/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-0.0.1-hello-world
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/instance: demo-0.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world
      app.kubernetes.io/instance: demo-0.0.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world
        app.kubernetes.io/instance: demo-0.0.1
    spec:
      containers:
      - name: hello-world
        image: "hello-world:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
