apiVersion: v1
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJwb21hLWNvbnRhaW5lcnMtZ3JvdXAuaW1ncmVwby5uZXh1cy5jei5pbnRhcHAuZXU6ODQ0MyI6IHsKICAgICAgICAgICAgImF1dGgiOiAiTVZsNFRXUlBRMHM2YTNBNWFHa3RjbkpNWnpKWWVXZG1WR2s0VFd4MVpITlJWSFJZYm1Sa1lURk5iMjB6UjFVeVJsSlRaRGc9IgogICAgICAgIH0KICAgIH0KfQo=
kind: Secret
metadata:
  name: poma-containers-group-pull-secret
type: kubernetes.io/dockerconfigjson
